<?xml version="1.0" encoding="us-ascii"?>
<GameState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <name>check0_ob_2</name>
  <Level>1</Level>
  <Check_x0020_Point>0</Check_x0020_Point>
  <Players>
    <Player>
      <In_x0020_Control>true</In_x0020_Control>
      <level>2</level>
      <experience>6</experience>
      <statPoints>4</statPoints>
      <strength>5</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>1</id>
    </Player>
    <Player>
      <In_x0020_Control>false</In_x0020_Control>
      <level>2</level>
      <experience>6</experience>
      <statPoints>8</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>2</id>
    </Player>
    <Player>
      <In_x0020_Control>false</In_x0020_Control>
      <level>2</level>
      <experience>6</experience>
      <statPoints>8</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>3</id>
    </Player>
    <Player>
      <In_x0020_Control>false</In_x0020_Control>
      <level>2</level>
      <experience>6</experience>
      <statPoints>8</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>4</id>
    </Player>
  </Players>
  <Objectives>
    <objectives>true</objectives>
    <objectives>true</objectives>
    <objectives>false</objectives>
    <objectives>false</objectives>
    <objectives>false</objectives>
    <objectives>false</objectives>
  </Objectives>
</GameState>