<?xml version="1.0" encoding="Windows-1252"?>
<GameState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Level>1</Level>
  <Check_x0020_Point>0</Check_x0020_Point>
  <Players>
    <Player>
      <In_x0020_Control>true</In_x0020_Control>
      <level>1</level>
      <experience>3</experience>
      <statPoints>5</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>1</id>
      <health>100</health>
      <energy>100</energy>
      <Abilities>
        <Ability>0</Ability>
        <Ability>0</Ability>
        <Ability>0</Ability>
        <Ability>0</Ability>
      </Abilities>
      <basic>1</basic>
    </Player>
    <Player>
      <In_x0020_Control>false</In_x0020_Control>
      <level>1</level>
      <experience>3</experience>
      <statPoints>5</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>2</id>
      <health>100</health>
      <energy>100</energy>
      <Abilities>
        <Ability>0</Ability>
        <Ability>0</Ability>
        <Ability>0</Ability>
        <Ability>0</Ability>
      </Abilities>
      <basic>1</basic>
    </Player>
    <Player>
      <In_x0020_Control>false</In_x0020_Control>
      <level>1</level>
      <experience>3</experience>
      <statPoints>5</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>3</id>
      <health>100</health>
      <energy>100</energy>
      <Abilities>
        <Ability>0</Ability>
        <Ability>0</Ability>
        <Ability>0</Ability>
        <Ability>0</Ability>
      </Abilities>
      <basic>1</basic>
    </Player>
    <Player>
      <In_x0020_Control>false</In_x0020_Control>
      <level>1</level>
      <experience>3</experience>
      <statPoints>5</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>4</id>
      <health>100</health>
      <energy>100</energy>
      <Abilities>
        <Ability>0</Ability>
        <Ability>0</Ability>
        <Ability>0</Ability>
        <Ability>0</Ability>
      </Abilities>
      <basic>1</basic>
    </Player>
  </Players>
  <Objectives>
    <objectives>false</objectives>
    <objectives>false</objectives>
    <objectives>false</objectives>
    <objectives>false</objectives>
    <objectives>false</objectives>
    <objectives>false</objectives>
  </Objectives>
  <SaveSlot>2</SaveSlot>
  <Date>4/19/2017 4:38:06 PM</Date>
</GameState>