<?xml version="1.0" encoding="Windows-1252"?>
<GameState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <name>check3_ob_6</name>
  <Level>1</Level>
  <Check_x0020_Point>3</Check_x0020_Point>
  <Players>
    <Player>
      <In_x0020_Control>true</In_x0020_Control>
      <level>1</level>
      <experience>0</experience>
      <statPoints>5</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>1</id>
    </Player>
    <Player>
      <In_x0020_Control>false</In_x0020_Control>
      <level>1</level>
      <experience>0</experience>
      <statPoints>5</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>2</id>
    </Player>
    <Player>
      <In_x0020_Control>false</In_x0020_Control>
      <level>1</level>
      <experience>0</experience>
      <statPoints>5</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>3</id>
    </Player>
    <Player>
      <In_x0020_Control>false</In_x0020_Control>
      <level>1</level>
      <experience>0</experience>
      <statPoints>5</statPoints>
      <strength>1</strength>
      <intelligence>1</intelligence>
      <stamina>1</stamina>
      <id>4</id>
    </Player>
  </Players>
  <Objectives>
    <objectives>true</objectives>
    <objectives>true</objectives>
    <objectives>true</objectives>
    <objectives>true</objectives>
    <objectives>true</objectives>
    <objectives>true</objectives>
  </Objectives>
</GameState>